### PR TITLE
Add error monitoring section to privacy policy, dynamic confirmation popup in the ap

### PR DESCRIPTION
**Pull request by mclrc**

### CODE REVIEW

**Review by johan-t — COMMENTED** [review]
Is it still fine if we report the data of the people who have not accepted the privacy policy? 

Because at least for the web app right now only people who have submitted a report have accepted the privacy policy.

**Comment by johan-t** [comment]
Is there anything else we need to use sentry in a GdpR compliant way?

**Comment by mclrc** [comment]
I configured sentry to not store IPs, we should be good on the GDPR front. I will add a privacy policy version file to public so that we can check in the app if the user confirmed the current version

**Comment by johan-t** [comment]
@mclrc I mean as long as we dont store any data with which a person can be identified we should be good to go.

**Review by johan-t — APPROVED** [review]

**Comment by johan-t** [comment]
@mclrc What does the dynamic privacy policy date solve or why did you choose to implement it?

**Comment by mclrc** [comment]
@johan-t I implemented a dynamic blocking popup in the app that checks the confirmed and most recent privacy policy versions and forces users to accept the new one before using the app. this means we don't need to ship app updates (and have them reviewed + pushed out to all users) before we change something that requires a change to the privacy policy.

**Pull request merged**
